In [1]:
import pandas as pd
import numpy as np

In [10]:
[(i+i, i*i) for i in range(1,101)]

# s = map(lambda x: (x+x, x*x),range(1,101))
# print(s)

[(2, 1),
 (4, 4),
 (6, 9),
 (8, 16),
 (10, 25),
 (12, 36),
 (14, 49),
 (16, 64),
 (18, 81),
 (20, 100),
 (22, 121),
 (24, 144),
 (26, 169),
 (28, 196),
 (30, 225),
 (32, 256),
 (34, 289),
 (36, 324),
 (38, 361),
 (40, 400),
 (42, 441),
 (44, 484),
 (46, 529),
 (48, 576),
 (50, 625),
 (52, 676),
 (54, 729),
 (56, 784),
 (58, 841),
 (60, 900),
 (62, 961),
 (64, 1024),
 (66, 1089),
 (68, 1156),
 (70, 1225),
 (72, 1296),
 (74, 1369),
 (76, 1444),
 (78, 1521),
 (80, 1600),
 (82, 1681),
 (84, 1764),
 (86, 1849),
 (88, 1936),
 (90, 2025),
 (92, 2116),
 (94, 2209),
 (96, 2304),
 (98, 2401),
 (100, 2500),
 (102, 2601),
 (104, 2704),
 (106, 2809),
 (108, 2916),
 (110, 3025),
 (112, 3136),
 (114, 3249),
 (116, 3364),
 (118, 3481),
 (120, 3600),
 (122, 3721),
 (124, 3844),
 (126, 3969),
 (128, 4096),
 (130, 4225),
 (132, 4356),
 (134, 4489),
 (136, 4624),
 (138, 4761),
 (140, 4900),
 (142, 5041),
 (144, 5184),
 (146, 5329),
 (148, 5476),
 (150, 5625),
 (152, 5776),
 (154, 5929),
 (156, 6084),
 (158, 6241),
 (160, 6400),
 (162, 6561),
 (164, 6724),
 (166, 6889),
 (168, 7056),
 (170, 7225),
 (172, 7396),
 (174, 7569),
 (176, 7744),
 (178, 7921),
 (180, 8100),
 (182, 8281),
 (184, 8464),
 (186, 8649),
 (188, 8836),
 (190, 9025),
 (192, 9216),
 (194, 9409),
 (196, 9604),
 (198, 9801),
 (200, 10000)]

In [12]:
[(i+i, i*i) for i in range(1,101) if i%3==0 or i%5==0 ]

[(6, 9),
 (10, 25),
 (12, 36),
 (18, 81),
 (20, 100),
 (24, 144),
 (30, 225),
 (36, 324),
 (40, 400),
 (42, 441),
 (48, 576),
 (50, 625),
 (54, 729),
 (60, 900),
 (66, 1089),
 (70, 1225),
 (72, 1296),
 (78, 1521),
 (80, 1600),
 (84, 1764),
 (90, 2025),
 (96, 2304),
 (100, 2500),
 (102, 2601),
 (108, 2916),
 (110, 3025),
 (114, 3249),
 (120, 3600),
 (126, 3969),
 (130, 4225),
 (132, 4356),
 (138, 4761),
 (140, 4900),
 (144, 5184),
 (150, 5625),
 (156, 6084),
 (160, 6400),
 (162, 6561),
 (168, 7056),
 (170, 7225),
 (174, 7569),
 (180, 8100),
 (186, 8649),
 (190, 9025),
 (192, 9216),
 (198, 9801),
 (200, 10000)]

In [14]:
list(map(lambda x: (x+x,x*x), range(1,101)))

[(2, 1),
 (4, 4),
 (6, 9),
 (8, 16),
 (10, 25),
 (12, 36),
 (14, 49),
 (16, 64),
 (18, 81),
 (20, 100),
 (22, 121),
 (24, 144),
 (26, 169),
 (28, 196),
 (30, 225),
 (32, 256),
 (34, 289),
 (36, 324),
 (38, 361),
 (40, 400),
 (42, 441),
 (44, 484),
 (46, 529),
 (48, 576),
 (50, 625),
 (52, 676),
 (54, 729),
 (56, 784),
 (58, 841),
 (60, 900),
 (62, 961),
 (64, 1024),
 (66, 1089),
 (68, 1156),
 (70, 1225),
 (72, 1296),
 (74, 1369),
 (76, 1444),
 (78, 1521),
 (80, 1600),
 (82, 1681),
 (84, 1764),
 (86, 1849),
 (88, 1936),
 (90, 2025),
 (92, 2116),
 (94, 2209),
 (96, 2304),
 (98, 2401),
 (100, 2500),
 (102, 2601),
 (104, 2704),
 (106, 2809),
 (108, 2916),
 (110, 3025),
 (112, 3136),
 (114, 3249),
 (116, 3364),
 (118, 3481),
 (120, 3600),
 (122, 3721),
 (124, 3844),
 (126, 3969),
 (128, 4096),
 (130, 4225),
 (132, 4356),
 (134, 4489),
 (136, 4624),
 (138, 4761),
 (140, 4900),
 (142, 5041),
 (144, 5184),
 (146, 5329),
 (148, 5476),
 (150, 5625),
 (152, 5776),
 (154, 5929),
 (156, 6084),
 (158, 6241),
 (160, 6400),
 (162, 6561),
 (164, 6724),
 (166, 6889),
 (168, 7056),
 (170, 7225),
 (172, 7396),
 (174, 7569),
 (176, 7744),
 (178, 7921),
 (180, 8100),
 (182, 8281),
 (184, 8464),
 (186, 8649),
 (188, 8836),
 (190, 9025),
 (192, 9216),
 (194, 9409),
 (196, 9604),
 (198, 9801),
 (200, 10000)]

In [20]:
list(map(lambda x: (x+x,x*x), filter(lambda x: x % 3 == 0 or x%5==0, range(1,101))))

[(6, 9),
 (10, 25),
 (12, 36),
 (18, 81),
 (20, 100),
 (24, 144),
 (30, 225),
 (36, 324),
 (40, 400),
 (42, 441),
 (48, 576),
 (50, 625),
 (54, 729),
 (60, 900),
 (66, 1089),
 (70, 1225),
 (72, 1296),
 (78, 1521),
 (80, 1600),
 (84, 1764),
 (90, 2025),
 (96, 2304),
 (100, 2500),
 (102, 2601),
 (108, 2916),
 (110, 3025),
 (114, 3249),
 (120, 3600),
 (126, 3969),
 (130, 4225),
 (132, 4356),
 (138, 4761),
 (140, 4900),
 (144, 5184),
 (150, 5625),
 (156, 6084),
 (160, 6400),
 (162, 6561),
 (168, 7056),
 (170, 7225),
 (174, 7569),
 (180, 8100),
 (186, 8649),
 (190, 9025),
 (192, 9216),
 (198, 9801),
 (200, 10000)]

In [40]:
s = " you are a terrible person, and you should probably be removed from all teaching positions i am in awe. i may not like it, but this is what peak performance looks like As one of your students, should I be concerned? oh my gOD You can teach CS or kindergarten English. I want to take your class "

c ={}
for ch in s.split(' '):
    ch = ch.lower()
    if not c.__contains__(ch):
        c[ch] = 1
    else:
         c[ch] += 1

result = sorted(c.items() , key=lambda t : t[1], reverse=True)

print(result)

[('i', 4), ('you', 3), ('', 2), ('should', 2), ('be', 2), ('like', 2), ('your', 2), ('are', 1), ('a', 1), ('terrible', 1), ('person,', 1), ('and', 1), ('probably', 1), ('removed', 1), ('from', 1), ('all', 1), ('teaching', 1), ('positions', 1), ('am', 1), ('in', 1), ('awe.', 1), ('may', 1), ('not', 1), ('it,', 1), ('but', 1), ('this', 1), ('is', 1), ('what', 1), ('peak', 1), ('performance', 1), ('looks', 1), ('as', 1), ('one', 1), ('of', 1), ('students,', 1), ('concerned?', 1), ('oh', 1), ('my', 1), ('god', 1), ('can', 1), ('teach', 1), ('cs', 1), ('or', 1), ('kindergarten', 1), ('english.', 1), ('want', 1), ('to', 1), ('take', 1), ('class', 1)]

In [15]:

def longestPalindrome(s):
    
    max = s[0]
    
    
    for i in range(0,len(s)):
        
        j = len(s)

        while i<j:

            temp = s[i:j] 
            print(temp)
            
            if temp == temp[::-1] and len(temp) > len(max):
                            max = temp
            j-=1
                            
                        

    return max
print(longestPalindrome("babad"))

babad
baba
bab
ba
b
abad
aba
ab
a
bad
ba
b
ad
a
d
bab

NameError: name 'longestPalindrome' is not defined